---
##playbook to install packages

- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  vars:
    driver: 440.31
    driver_url: http://us.download.nvidia.com/XFree86/Linux-x86_64/440.31/NVIDIA-Linux-x86_64-440.31.run
  tasks:
    - get_url: dest=. url={{driver_url}}
    - name: Install nvidia-driver
      apt:
        name: Install nvidia-driver
        update_cache: yes 
