---
##playbook to install nvidia_driver without any roles
- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: install nvidia_driver
      apt:
      autoremove: yes
      cache_valid_time: 300
      state: present
      update_cache: yes
      pkg:
        - nvidia-driver-435
