---
# tasks file for nvidia-driver
- name: Add Nvidia Repository
  apt_repository: repo='ppa:graphics-drivers' state=present
  register: ppastable

- name: Remove nvidia
  apt: pkg={{item}} state=absent purge=yes force=yes
  with_items:
  - nvidia*

- name: install nvidia
  apt: pkg=nvidia-driver-430 state=installed update_cache=true

- name: reboot the sever
  reboot:
